### ISSUE TITLE
Plugin決めるぞ

### ISSUE THREAD

**Issue by eraser5th** [matumoto1234/my-docsify-template#1]

**Comment by eraser5th** [comment]
次のページ、前のページのボタン追加
https://github.com/imyelo/docsify-pagination

**Comment by eraser5th** [comment]
タブのサポート
https://jhildenbiddle.github.io/docsify-tabs/#/

**Comment by eraser5th** [comment]
アラートのサポート
https://github.com/fzankl/docsify-plugin-flexible-alerts

**Comment by eraser5th** [comment]
コメント関連。いっぱいあるので一旦ここに上げてく
- https://github.com/ndom91/docsify-commento
-

**Comment by eraser5th** [comment]
パネルのサポート。十分な幅がある時に横並びのコンテンツを表示することができる。
https://github.com/VagnerDomingues/docsify-example-panels

**Comment by matumoto1234** [comment]
https://docsify.js.org/#/awesome?id=plugins

**Comment by eraser5th** [comment]
まーめいどサポート
https://github.com/Leward/mermaid-docsify

**Comment by eraser5th** [comment]
サイドバーのフォルダ風折り畳みのサポート。正直好みによる
https://github.com/iPeng6/docsify-sidebar-collapse

**Comment by eraser5th** [comment]
折り畳み。スター数が少ないのが気になる。
https://github.com/atleastzero/docsify-accordify

**Comment by eraser5th** [comment]
JSのREPLを埋め込む。
https://jhildenbiddle.github.io/docsify-plugin-runkit/#/

**Comment by eraser5th** [comment]
Docsify上でライブコーディングができる？ちょっと試してみたい
https://github.com/kossidts/docsify-live-demo

**Comment by eraser5th** [comment]
カスタマイズ可能なテーマ
https://jhildenbiddle.github.io/docsify-themeable/#/

**Comment by matumoto1234** [comment]
進行度の表示
https://github.com/HerbertHe/docsify-progress

![image](https://user-images.githubusercontent.com/55180183/227595282-20eda001-5219-4f5d-8486-b33ad573c9bb.png)

**Comment by eraser5th** [comment]
コードのコピー
https://github.com/jperasmus/docsify-copy-code
